### ISSUE TITLE
Remove references to unsafeWindow at request of AMO reviewers

### ISSUE THREAD

**Issue by sidstamm** [WrightJosh/SeniorProject#28]
unsafeWindow is used in data/scripts/inject.js, and if possible should be removed.  What's it used for?

https://blog.mozilla.org/addons/2014/04/10/changes-to-unsafewindow-for-the-add-on-sdk/

**Comment by MasonSchneider** [comment]
Just to let you know, we submitted a new review because we wanted to remove the non-functional button for View all certs. 
UnsafeWindow is there because we needed to allow the add-on to populate the cert info on the front-end. It looks like the fix detailed in your article should be fairly simple to implement.

**Comment by sidstamm** [comment]
Ok.  In general, ignoring the reviewer's suggestions is not helpful towards getting approved.  Fixing this will probably help with review times and such.

**Comment by MasonSchneider** [comment]
Yeah, in the initial feedback they made it sound as if it was more of an inconvenience rather than something we would be required to fix.

**Comment by sidstamm** [comment]
"You really should not" written in the review might be code for "fix this".

**Comment by sidstamm** [comment]
FWIW, in the review for 1.0.2, it said "please fix for next time"
