### ISSUE TITLE
Issue importing Certs in Developer Edition

### ISSUE THREAD

**Issue by burchtm** [WrightJosh/SeniorProject#33]
I am currently having an issue with importing certificates using the developer edition. The addon is working in the regular version of Firefox fine. I'm not sure what is causing this issue and will try to reproduce it on another computer as this may be a computer issue and not an addon issue.

**Comment by burchtm** [comment]
I am having this issue in both the development version and production versions of the addon

**Comment by burchtm** [comment]
Found differences

Developer Edition has extra authority "Krajowa Izba Rozliczeniowa S.A." and the authority "Autoridad de Certificacion Firmaprofesional CIF A62634068" shows blank instead of the name for some reason on the development version. The regular edition has the extra authority "NetLock Halozatbiztonsagi Kft"

The blank authority may be caused by changes in how names are shown when adding the "View All" button but I'm not sure. Still haven't discovered what is causing the overall issue.

**Comment by burchtm** [comment]
I am using Developer Edition 47.0a2 and Regular Edition 45.0.1

**Comment by sidstamm** [comment]
If this was breaking because of importCertsFromFile(), it's probably due to the removal of the function's first arg in this changeset:
http://hg.mozilla.org/mozilla-central/rev/62d300c9c733

This is a breaking change to an interface in Firefox, which means it'll surface in all flavors of Firefox in the future.  :(

I hate to suggest this hack, but maybe if you use a try block with the old one and if it doesn't work, catch the exception and use the new function.

**Comment by WilsonKathleen** [comment]
Regarding: Developer Edition has extra authority "Krajowa Izba Rozliczeniowa S.A." and the authority "Autoridad de Certificacion Firmaprofesional CIF A62634068" shows blank instead of the name for some reason on the development version. The regular edition has the extra authority "NetLock Halozatbiztonsagi Kft"

Indeed, the KIR root certificate was added in Firefox 46, and other root certificates were added and removed. Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1247990

The Cert Manager Add-On needs to be able to handle having the root store change out underneath it, depending on which version of Firefox is being run. We add, remove, and change trust bits for root certificates frequently.

The data in the CSV file that is generated from Salesforce may not be in sync with the particular version of Firefox that the user is running. The code should be able to deal with such differences.

**Comment by burchtm** [comment]
Resolved using the suggested try-catch in changeset f1f9a90b59ba6370246748e0482fb797fd3e2ddd and commented in 3be46f3a7b30b3b84e646ca0f363856c88fb489d.
