### ISSUE TITLE
View All button not working

### ISSUE THREAD

**Issue by WilsonKathleen** [WrightJosh/SeniorProject#40]
When I click on the View All button, it shows an empty list.
I'm using Firefox 46.

**Comment by burchtm** [comment]
We will look into this. Not sure what is causing it. I will try to download Firefox 46. It is working for me on Firefox 45 and Developer Edition 47.

**Comment by burchtm** [comment]
I have recreated the bug with 46. No logging is occurring as to why this is happening so I am going to research more and try to figure this out.

**Comment by burchtm** [comment]
Though the current XPI is not working with Firefox 46, the current development version is working when ran with JPM. I'm going to table this issue as it may have been fixed by some other change made after the creation of the XPI.

**Comment by burchtm** [comment]
This appears to be an XPI issue. The code is working when ran under "jpm run" via the terminal. However, when the XPI is packaged and installed via sideloading the "View All" button isn't working. I will look into why this is happening.

**Comment by burchtm** [comment]
This has been resolved. It ended up not being an issue with the XPI packaging but with a flawed assumption of the format of a certificate's nickname. This was silently affecting the list of certificates for an authority but wasn't as prominent and was overlooked. Both issues have been resolved with this. It wasn't happening in the development environment as the bug was only affecting some custom certificates and jpm creates a fresh profile thus wiping the custom certs from being used.
